// Single source of truth. Every app (and later the real AI assistant) reads from here.

export const profile = {
  name: 'Rafiur Rahman',
  title: 'Consultant • Data • AI • Software',
  tagline: 'I build data and AI products end to end, from messy source systems to shipped features.',
  location: 'United Kingdom',
  email: 'rafiurrahman1234@icloud.com',
}

export interface Project {
  slug: string
  title: string
  summary: string
  role: string
  period: string
  tech: string[]
  categories: string[]
  difficulty: 1 | 2 | 3 | 4 | 5
  outcomes: string[]
}

export const projects: Project[] = [
  {
    slug: 'semantic-document-search',
    title: 'Semantic Document Search',
    summary:
      'Natural-language search over a large internal document store using embeddings and a vector index.',
    role: 'Lead developer',
    period: '2026',
    tech: ['Azure OpenAI', 'Python', 'pgvector', 'FastAPI'],
    categories: ['AI', 'Data'],
    difficulty: 5,
    outcomes: [
      'Cut document lookup time from minutes to seconds',
      'Adopted by 3 internal teams',
    ],
  },
  {
    slug: 'analytics-pipeline',
    title: 'Automated Analytics Pipeline',
    summary:
      'Replaced manual spreadsheet reporting with a scheduled pipeline and a live dashboard.',
    role: 'Data consultant',
    period: '2025',
    tech: ['dbt', 'Snowflake', 'Airflow', 'Power BI'],
    categories: ['Data'],
    difficulty: 3,
    outcomes: ['Saved ~10 analyst hours per week', 'Single source of truth for KPIs'],
  },
  {
    slug: 'this-portfolio',
    title: 'This Portfolio',
    summary:
      'An interactive "digital workspace" portfolio with a window manager, apps, and a portfolio AI.',
    role: 'Designer & developer',
    period: '2026',
    tech: ['React', 'TypeScript', 'Zustand', 'Framer Motion', 'Tailwind'],
    categories: ['Software', 'AI'],
    difficulty: 2,
    outcomes: ['The portfolio is itself a portfolio project'],
  },
]

export interface ActivityItem {
  when: string
  label: string
}

export const activity: ActivityItem[] = [
  { when: '17:31', label: 'Built semantic document search' },
  { when: '16:42', label: 'Experimented with Azure OpenAI' },
  { when: 'Yesterday', label: 'Shipped new portfolio feature' },
  { when: '2026', label: 'Completed AI certification' },
]

export const skills: Record<string, string[]> = {
  'Data': ['SQL', 'dbt', 'Snowflake', 'Airflow', 'Power BI'],
  'AI': ['Azure OpenAI', 'Embeddings / RAG', 'Prompt engineering', 'LangChain'],
  'Software': ['React', 'TypeScript', 'Python', 'FastAPI', 'Git'],
}

export interface ExperienceItem {
  company: string
  role: string
  period: string
  location?: string
  highlights: string[]
}

/* PLACEHOLDER - replace with real roles. Everything that shows work history
   (the `experience` terminal command, the CV command, the /experience folder in
   the terminal filesystem) reads from this array. */
export const experience: ExperienceItem[] = [
  {
    company: 'Placeholder Consulting',
    role: 'Data & AI Consultant',
    period: '2024 - Present',
    location: 'United Kingdom',
    highlights: [
      'Led delivery of a semantic document search platform adopted by several internal teams.',
      'Built automated analytics pipelines that replaced manual spreadsheet reporting.',
    ],
  },
  {
    company: 'Placeholder Software Co.',
    role: 'Software Engineer',
    period: '2022 - 2024',
    highlights: ['Shipped internal tools and data services used across the business.'],
  },
]

export interface Certification {
  name: string
  issuer: string
  year: string
  credentialUrl?: string
}

/* PLACEHOLDER - replace with real certifications. */
export const certifications: Certification[] = [
  { name: 'Placeholder AI Engineering Certificate', issuer: 'Placeholder Institute', year: '2026' },
  { name: 'Placeholder Cloud Data Certificate', issuer: 'Placeholder Cloud', year: '2025' },
]

/* External links. An empty string means "not published yet" - commands and apps
   handle that gracefully. `cv` is a path/URL to a PDF once one exists. */
export const links = {
  github: 'https://github.com/Rafiur9Rahman',
  linkedin: '',
  repo: 'https://github.com/Rafiur9Rahman/digital-workspace-portfolio',
  cv: '',
}

/* ---------------------------------------------------------------------------
   Workspace Map graph. Nodes are generated by src/lib/workspaceGraph.ts from
   the arrays above; this section only adds the relationships a `tech[]` list
   can't express.

   Node ids:
     skill:<slug>      a leaf in `skills`, or a tech from a project's `tech[]`
     project:<slug>    projects[].slug
     exp:<company>     slug of experience[].company
     cert:<name>       slug of certifications[].name
     profile           the person, at the centre

   A project's `tech[]` entries auto-link to `skill:<slug>` and auto-create a
   tech node if that skill isn't in `skills`. Any `skill:` id referenced only
   here is created too; give it a real label via `graphLabels`.
--------------------------------------------------------------------------- */

export interface GraphRelation {
  from: string
  to: string
  /** why the two connect, shown on the edge */
  label?: string
}

/** Labels for skill / platform nodes that exist only in `relations`. */
export const graphLabels: Record<string, string> = {
  'skill:azure': 'Azure',
  'skill:azure-ai-search': 'Azure AI Search',
  'skill:blob-storage': 'Blob Storage',
}

export const relations: GraphRelation[] = [
  // Azure platform: the services roll up into one hub
  { from: 'skill:azure-openai', to: 'skill:azure', label: 'Azure service' },
  { from: 'skill:azure-ai-search', to: 'skill:azure', label: 'Azure service' },
  { from: 'skill:blob-storage', to: 'skill:azure', label: 'Azure storage' },
  { from: 'skill:embeddings-rag', to: 'skill:azure-openai', label: 'embeddings via Azure OpenAI' },

  // Projects -> skills / platforms beyond their tech list
  { from: 'project:semantic-document-search', to: 'skill:azure', label: 'runs on Azure' },
  { from: 'project:semantic-document-search', to: 'skill:embeddings-rag', label: 'retrieval-augmented search' },
  { from: 'project:semantic-document-search', to: 'skill:azure-ai-search', label: 'vector index' },
  { from: 'project:semantic-document-search', to: 'skill:blob-storage', label: 'document store' },

  // Experience -> projects and skills (placeholder roles for now)
  { from: 'exp:placeholder-consulting', to: 'project:semantic-document-search', label: 'led delivery' },
  { from: 'exp:placeholder-consulting', to: 'project:analytics-pipeline', label: 'built the pipeline' },
  { from: 'exp:placeholder-consulting', to: 'skill:azure', label: 'Azure data and AI work' },
  { from: 'exp:placeholder-consulting', to: 'skill:python', label: 'rule-based and semantic classification' },
  { from: 'exp:placeholder-software-co', to: 'project:this-portfolio', label: 'tooling background' },
  { from: 'exp:placeholder-software-co', to: 'skill:typescript', label: 'internal tools and services' },

  // Certifications -> skills (placeholder certs for now)
  { from: 'cert:placeholder-ai-engineering-certificate', to: 'skill:azure', label: 'Azure AI certification' },
  { from: 'cert:placeholder-ai-engineering-certificate', to: 'skill:azure-openai' },
  { from: 'cert:placeholder-ai-engineering-certificate', to: 'skill:embeddings-rag' },
  { from: 'cert:placeholder-cloud-data-certificate', to: 'skill:azure', label: 'cloud data certification' },
  { from: 'cert:placeholder-cloud-data-certificate', to: 'skill:snowflake' },

  // Profile -> the career spine
  { from: 'profile', to: 'exp:placeholder-consulting' },
  { from: 'profile', to: 'exp:placeholder-software-co' },
]
